server:
  port: 8787

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/qatar?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: soccer
    password: soccer
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      use-new-id-generate-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true